# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mariadb

    hostname: db
    ports:
      - 3306:3306

    restart: always

    environment:
      - MARIADB_DATABASE=sites_man_db
      - MARIADB_ROOT_PASSWORD=root 
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass


    volumes:
      - mariadb-volume:/var/lib/mysql/
      
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    
    hostname: api
    ports:
      - 8000:8000
    
    depends_on:
      - db
    
    restart: always
    
    environment:
      - MARIADB_DATABASE=sites_man_db
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass 
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./:/usr/app:ro

volumes:
  mariadb-volume: