name: Build

on: 
  push:
    paths:
      - src/**
  pull_request:
    paths:
      - src/**
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    
    env:
      MARIADB_USER: ${{secrets.MARIADB_USER}}
      MARIADB_PASSWORD: ${{secrets.MARIADB_PASSWORD}} 
      MARIADB_DATABASE: ${{secrets.MARIADB_DATABASE}}
      MARIADB_HOST: db
      MARIADB_PORT: ${{secrets.MARIADB_PORT}}
    
    services:
      db:
        image: mariadb
        env:
          MYSQL_USER: ${{secrets.MARIADB_USER}}
          MYSQL_PASSWORD: ${{secrets.MARIADB_PASSWORD}}
          MYSQL_DATABASE: ${{secrets.MARIADB_DATABASE}}
          MYSQL_ROOT_PASSWORD: ${{secrets.MARIADB_ROOT_PASSWORD}}
            
        ports:
          - ${{secrets.MARIADB_PORT}}  
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    container: python:3.10

    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: PYTHONPATH=${PYTHONPATH}:./src python -m pytest