name: Build

on: [push, pull_request]

env:
  MARIADB_USER: dev_user
  MARIADB_PASSWORD: dev_pass 
  MARIADB_DATABASE: sites_man_db
  MARIADB_HOST: mariadb
  MARIADB_PORT: 3306
  MYSQL_USER: dev_user
  MYSQL_PASSWORD: dev_pass
  MYSQL_DATABASE: sites_man_db
  MYSQL_ROOT_PASSWORD: root
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_USER: dev_user
          MARIADB_PASSWORD: dev_pass 
          MARIADB_DATABASE: sites_man_db
          MARIADB_HOST: db
          MARIADB_PORT: 3306
          MYSQL_USER: dev_user
          MYSQL_PASSWORD: dev_pass
          MYSQL_DATABASE: sites_man_db
          MYSQL_ROOT_PASSWORD: root
      
        ports:
          - 3306  
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health- =5s --health-retries=5

    container: python:3.10

    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          PYTHONPATH=${PYTHONPATH}:./src python -m pytest