name: Build

on: [push, pull_request]

job:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"