name: Build

on: [push, pull_request]

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt