name: Build

on: [push, pull_request]


jobs:
  my_job:
    env:
      MARIADB_USER: dev_user
      MARIADB_PASSWORD: dev_pass 
      MARIADB_DATABASE: sites_man_db
      MARIADB_HOST: 0.0.0.0
      MARIADB_PORT: 3306
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install mariadb-dev package
        run: sudo apt-get install libmariadb-dev
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: Wait for db container
        run: |
            while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
              sleep 1
            done    
      - name: test with pytest
        run: |
          PYTHONPATH=${PYTHONPATH}:./src python -m pytest