name: Deploy

on: 
  push:
    paths:
      - src/**
      - .github/workflows/deploy.yml
      - .github/workflows/build.yml

  pull_request:
    paths:
      - src/**

jobs:
  deploy_aws:
    uses: joaodiogo10/githubActions/.github/workflows/build.yml@main
    secrets: inherit
