name: Deploy


on:
  pull_request:
    branches:    
      - main
    paths:
      - src/**
      - .github/workflows/deploy.yml
    
  push:
    branches:    
      - main
    paths:
      - src/**
      - .github/workflows/deploy.yml

jobs:
  deploy_aws:
    uses: joaodiogo10/githubActions/.github/workflows/build.yml@development
    secrets: inherit
