name: Deploy

on: 
  push:
    paths:
      - src/**
      - .github/workflows/deploy.yml
      - .github/workflows/build.yml

  pull_request:
    paths:
      - src/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: joaodiogo10/githubActions/.github/workflows/build.yml@main
      with:
        MARIADB_USER: ${{ secrets.MARIADB_USER }}
        MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }} 
        MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
        MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
