name: Deploy

on:
  pull_request:
    branches:    
      - main
      - development
    paths:
      - src/**
      - .github/workflows/*
    
  push:
    branches:    
      - main
      - development
    paths:
      - src/**
      - .github/workflows/*

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    uses: joaodiogo10/githubActions/.github/workflows/build.yml@development
    secrets: inherit
  
  deploy_aws:
    needs: build_and_test
    steps:
      - name: test with pytest
        run: echo "Deploying..."