name: Deploy


on: 
  push:
    paths:
      - src/**
      - .github/workflows/deploy.yml

  pull_request:
    paths:
      - src/**

jobs:
  build:
    uses: joaodiogo10/githubActions/.github/workflows/build.yml@main
    